[project]
name = "rag-two-branch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "way00out", email = "way00out@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
]

[project.scripts]
rag-two-branch = "rag_two_branch:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
